version: "3"
volumes:
    db-data:

services:
  db:
    image: mysql:8.0.26
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=HC@password@123
      - MYSQL_DATABASE=hc
      #- MYSQL_USER=django
      #- MYSQL_PASSWORD=HC@password@123
    ports:
      - 3306:3306

  web:
    build:
        context: ..
        dockerfile: docker/Dockerfile
    env_file:
        - .env
    ports:
        - 8000:8000
    depends_on:
        - db
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 10; done; uwsgi /hlthchk/healthchecks/docker/uwsgi.ini'

